# Env files to populate vars (if no value set) in workspace
# Later declarations will replace first etc.
env_files:
  - .env
  - .env.dev

# variable_type:
#     env_var (default) | file | dotglci_manual
#         "dotglci_manual" will put it in pipeline variable, simulating manual run

# masked (default: false)
#     only if "env_var", see other limitations:
#     https://docs.gitlab.com/ee/ci/variables/#mask-a-cicd-variable

# env is the "environment_scope" of variable in the cicd (default, * = all)

# expanded: default true, (not "raw")

# protected

variables:
  - key: EXAMPLE_SET_VALUE
    variable_type: env_var
    masked: false
    value: |
      Multi line
      YAML
      Example1

  - key: VAR_X
    masked: false
    variable_type: env_var

  - key: VAR_Y
    masked: true
    protected: true
    variable_type: env_var

  - key: VAR_Z
    variable_type: env_var

  - key: MY_ENV
    variable_type: env_var

  - key: MY_FILE
    variable_type: file
    path: ".gitignore"

  - key: ENV_1
    variable_type: env_var
    value: env1_value
    env: env1
