tasks:
  - name: install-deno
    init: |
      export DENO_INSTALL="/home/gitpod/.deno" 
      export PATH="$DENO_INSTALL/bin:$PATH" 
      bash ./0deno-gitpod-install.sh
  - name: docker-status
    command: docker-compose ps

ports:
  - name: Gitlab
    port: 15080
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - denoland.vscode-deno
