version: '3.6'
services:

  helper:
    image: curlimages/curl:latest
    networks:
      - gitlab_ci_local

  runner1:
    image: gitlab/gitlab-runner:ubuntu
    environment:
      - XYZ=runner1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - runner1cfg:/etc/gitlab-runner/
    networks:
      - gitlab_ci_local

  runner2:
    image: gitlab/gitlab-runner:ubuntu
    environment:
      - XYZ=runner2
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - runner2cfg:/etc/gitlab-runner/
    networks:
      - gitlab_ci_local

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab
    container_name: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: LongComplexText0000!
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url "http://gitlab:80"
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['artifacts_path'] = "/mnt/ci/artifacts"
        gitlab_ci['builds_directory'] = '/mnt/ci/builds'
    ports:
      - '15080:80'
    shm_size: '256m'
    volumes:
      - ./data/:/mnt/ci/
    networks:
      - gitlab_ci_local
    #    volumes:
    #      - './data/config:/etc/gitlab'
    #      - './data/logs:/var/log/gitlab'
    #      - './data/data:/var/opt/gitlab'

volumes:
  runner1cfg:
  runner2cfg:


networks:
  gitlab_ci_local:
    name: gitlab_ci_local
    driver: bridge
