# If not empty, set custom path for the ".gitlab-ci.yml"
ci_yaml_path: ".gitlab-ci.yml"

# Env files to populate vars (if no value set) in workspace
# Later declarations will replace first etc.
env_files:
  - .env
  - .env.dev

# variable_type:
#     env_var (default) | file

# masked (default: false)
#     only if "env_var", see other limitations:
#     https://docs.gitlab.com/ee/ci/variables/#mask-a-cicd-variable

# env is the "environment_scope" of variable in the cicd (default, * = all)

# expanded: default true, (not "raw")

# protected

variables:
  - key: EXAMPLE_SET_VALUE
    variable_type: env_var
    masked: false
    value: |
      Multi line
      YAML
      Example1

  - key: VAR_X
    masked: false
    variable_type: env_var

  - key: VAR_Y
    masked: true
    protected: true
    variable_type: env_var

  - key: VAR_Z
    variable_type: env_var

  - key: MY_ENV
    variable_type: env_var

  - key: MY_FILE
    variable_type: file
    path: ".gitignore"

  - key: ENV_1
    variable_type: env_var
    value: env1_value
    env_scope: env1

# Secure files
# max 100 files, max 5 mb
# https://docs.gitlab.com/ee/api/secure_files.html

#secure_files:
#  - name:
#    path:

# Manual pipelines to wait for on run
# `manual_vars` have value path or from envfile but not protected, expended, mask, gitlab_proj_env
# If null/empty, will wait for latest pipeline after push
#     If no runs, or latest is done, will exit (because we assume no pipeline is configured in .gitlab-ci.yml)

manual_pipelines:
  - git_ref: master
    manual_vars:
      - key: name
        variable_type: file | env_var (default)
